import type { MasterKomunitasSeedItem } from "./tegal-data";

function slugify(text: string): string {
  return (text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export interface RawPaudItem {
  nama: string;
  kecamatan: string;
  kelurahan: string;
  jenis_institusi?: "TK" | "KB" | "RA" | "SPS" | "TPA" | "PKBM" | "SKB";
  rt?: string;
  rw?: string;
  jadwal?: string;
  kontak?: string;
  lokasi?: string;
  deskripsi?: string;
}

// Data Lengkap Resmi Satuan PAUD (TK, KB, RA, SPS, TPA), PKBM, dan Sanggar Kegiatan Belajar (SKB) se-Kota Tegal
export const RAW_PAUD_PKBM_TEGAL: RawPaudItem[] = [
  // ==========================================
  // 1. KECAMATAN TEGAL TIMUR (5 Kelurahan)
  // ==========================================
  // Panggung (Terminal, Pesisir & Lingkungan Warga)
  {
    nama: "RA Sakila Kerti Terminal Tegal",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    jenis_institusi: "RA",
    rw: "01",
    rt: "03",
    lokasi: "Kompleks Terminal Bus Tegal, Jl. Kolonel Sugiono, Panggung, Tegal Timur, Kota Tegal",
    deskripsi: "Raudhatul Athfal rujukan inklusif berbasis pemberdayaan warga pesisir & terminal dengan pendidikan karakter terpadu dan stimulasi tumbuh kembang anak usia dini.",
    kontak: "0812-2998-3344 (Dr. Yusqon - Pengelola)",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "PKBM Sakila Kerti Kota Tegal",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    jenis_institusi: "PKBM",
    rw: "01",
    rt: "04",
    lokasi: "Kompleks Terminal Tegal & Pesisir Pantai, Panggung, Tegal Timur, Kota Tegal",
    deskripsi: "Pusat Kegiatan Belajar Masyarakat peraih penghargaan nasional yang menyelenggarakan PAUD Inklusif, Keaksaraan Fungsional, Kesetaraan Paket A/B/C, dan Pelatihan Kecakapan Hidup.",
    kontak: "0813-9008-8776 (Sekretariat PKBM)",
    jadwal: "Senin s/d Sabtu, Pukul 08.00 - 15.30 WIB",
  },
  {
    nama: "TK Pertiwi Panggung",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    jenis_institusi: "TK",
    rw: "02",
    rt: "02",
    lokasi: "Jl. Veteran No. 12, Panggung, Tegal Timur, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak formal binaan Yayasan Pertiwi dengan kurikulum merdeka bermain, penguatan motorik, dan pembentukan budi pekerti luhur.",
    kontak: "0815-6677-8899",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "KB Cahaya Bintang Panggung",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    jenis_institusi: "KB",
    rw: "03",
    rt: "01",
    lokasi: "Jl. Panggung Baru No. 45, Panggung, Tegal Timur, Kota Tegal",
    deskripsi: "Kelompok Bermain usia 2-4 tahun yang menitikberatkan pada sosialisasi, stimulasi motorik halus-kasar, serta pengenalan literasi dasar.",
    kontak: "0878-1122-3344",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal 1 Panggung",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    jenis_institusi: "TK",
    rw: "04",
    rt: "03",
    lokasi: "Jl. Martoloyo No. 88, Panggung, Tegal Timur, Kota Tegal",
    deskripsi: "TK Islam berbasis penanaman akidah, hafalan doa harian, dan pembiasaan akhlak mulia sejak usia dini.",
    kontak: "0813-2211-4455",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "TPA Sakila Kerti Pesisir",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    jenis_institusi: "TPA",
    rw: "05",
    rt: "02",
    lokasi: "Kompleks PPI Pesisir Muara, Panggung, Tegal Timur, Kota Tegal",
    deskripsi: "Tempat Penitipan Anak dan pengasuhan ramah anak bagi keluarga nelayan dan pekerja sekitar pesisir.",
    kontak: "0812-9988-1122",
    jadwal: "Senin s/d Sabtu, Pukul 07.00 - 16.00 WIB",
  },
  {
    nama: "SPS Melati Bahari Panggung",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    jenis_institusi: "SPS",
    rw: "06",
    rt: "01",
    lokasi: "Balai RW 06 Panggung, Tegal Timur, Kota Tegal",
    deskripsi: "Satuan PAUD Sejenis terintegrasi Posyandu dan BKB untuk stimulasi deteksi dini tumbuh kembang balita.",
    kontak: "0857-4433-2211",
    jadwal: "Rabu dan Sabtu, Pukul 08.30 - 10.30 WIB",
  },

  // Kejambon
  {
    nama: "UPTD SPNF SKB Kota Tegal",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    jenis_institusi: "SKB",
    rw: "01",
    rt: "01",
    lokasi: "Jl. Wisanggeni No. 1, Kejambon, Tegal Timur, Kota Tegal",
    deskripsi: "Unit Pelaksana Teknis Daerah Satuan Pendidikan Nonformal Sanggar Kegiatan Belajar (UPTD SPNF SKB) Kota Tegal yang menyelenggarakan PAUD Percontohan, Pendidikan Kesetaraan Paket A, B, C, Keaksaraan Fungsional, dan Kursus Vokasi Mandiri.",
    kontak: "0283-356111 / 0812-2233-4455 (Kepala UPTD SPNF SKB)",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 15.30 WIB",
  },
  {
    nama: "TK Negeri Pembina Tegal Timur",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    jenis_institusi: "TK",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Pendidikan No. 5, Kejambon, Tegal Timur, Kota Tegal",
    deskripsi: "TK Negeri Percontohan Kota Tegal dengan sarana edukasi saintifik, area luar ruang motorik, dan pembinaan gizi anak usia dini.",
    kontak: "0283-356789 / 0812-4455-6677",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "KB / PAUD Pembina Kejambon",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    jenis_institusi: "KB",
    rw: "01",
    rt: "03",
    lokasi: "Kompleks TK Negeri Pembina, Jl. Pendidikan, Kejambon, Tegal Timur, Kota Tegal",
    deskripsi: "Kelompok bermain terpadu dengan stimulasi sensori motorik, pengenalan bahasa, dan kemandirian balita usia 2-4 tahun.",
    kontak: "0813-8877-6655",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal Kejambon",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    jenis_institusi: "TK",
    rw: "02",
    rt: "04",
    lokasi: "Jl. Wisanggeni No. 20, Kejambon, Tegal Timur, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Aisyiyah dengan kurikulum pembelajaran Islam terpadu, tahfidz juz 30 cilik, dan kreasi seni budaya.",
    kontak: "0856-7788-9900",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "PKBM Bina Insan Mandiri Kejambon",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    jenis_institusi: "PKBM",
    rw: "03",
    rt: "02",
    lokasi: "Jl. Sultan Agung No. 72, Kejambon, Tegal Timur, Kota Tegal",
    deskripsi: "Lembaga pendidikan non-formal yang melayani Kesetaraan Pendidikan Paket A/B/C, Keaksaraan Usaha Mandiri, dan Kursus Keterampilan Vokasi.",
    kontak: "0812-3344-9988",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 16.00 WIB",
  },
  {
    nama: "SPS Kemuning Indah Kejambon",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    jenis_institusi: "SPS",
    rw: "04",
    rt: "01",
    lokasi: "Balai RW 04 Kejambon, Tegal Timur, Kota Tegal",
    deskripsi: "Layanan PAUD Berbasis Masyarakat terintegrasi Posyandu Kemuning untuk pemantauan tumbuh kembang dan gizi balita.",
    kontak: "0877-5544-3322",
    jadwal: "Selasa dan Kamis, Pukul 08.30 - 10.30 WIB",
  },

  // Slerok
  {
    nama: "PAUD & KB Mutiara Hati Slerok",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    jenis_institusi: "KB",
    rw: "01",
    rt: "03",
    lokasi: "Jl. Slerok Asri No. 18, Slerok, Tegal Timur, Kota Tegal",
    deskripsi: "Layanan pendidikan anak usia dini holistik integratif berorientasi pada kecerdasan jamak dan kemandirian anak.",
    kontak: "0878-9900-1122",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 11.00 WIB",
  },
  {
    nama: "TK Al-Irsyad Slerok",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    jenis_institusi: "TK",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Werkudoro No. 34, Slerok, Tegal Timur, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Islam Al-Irsyad Al-Islamiyyah dengan kurikulum keagamaan kuat, pembiasaan adab harian, dan bilingual dasar.",
    kontak: "0283-358899 / 0812-7766-5544",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "TK Muslimat NU Slerok",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    jenis_institusi: "TK",
    rw: "03",
    rt: "02",
    lokasi: "Jl. Abimanyu No. 15, Slerok, Tegal Timur, Kota Tegal",
    deskripsi: "TK binaan Muslimat Nahdlatul Ulama yang mengedepankan nilai Ahlussunnah wal Jamaah dan cinta tanah air.",
    kontak: "0858-1122-3344",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "PKBM Mandiri Slerok Tegal",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    jenis_institusi: "PKBM",
    rw: "04",
    rt: "04",
    lokasi: "Jl. Nakula No. 27, Slerok, Tegal Timur, Kota Tegal",
    deskripsi: "Pusat Kegiatan Belajar Masyarakat penyedia program kesetaraan ijazah Paket A/B/C dan pelatihan wirausaha kuliner lokal.",
    kontak: "0813-4455-8899",
    jadwal: "Senin s/d Sabtu, Pukul 09.00 - 16.00 WIB",
  },
  {
    nama: "SPS Dahlia Slerok",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    jenis_institusi: "SPS",
    rw: "05",
    rt: "02",
    lokasi: "Balai RW 05 Slerok, Tegal Timur, Kota Tegal",
    deskripsi: "Layanan stimulasi bermain anak usia 1-4 tahun bersama kader posyandu binaan Puskesmas Slerok.",
    kontak: "0877-2233-4455",
    jadwal: "Senin dan Kamis, Pukul 08.30 - 10.30 WIB",
  },

  // Mintaragen
  {
    nama: "TK Kemala Bhayangkari 25 Mintaragen",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    jenis_institusi: "TK",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Yos Sudarso No. 10, Mintaragen, Tegal Timur, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Yayasan Kemala Bhayangkari dengan disiplin positif, edukasi keselamatan lalu lintas sejak dini, dan seni tari.",
    kontak: "0283-351234 / 0812-8899-0011",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "PAUD & KB Kasih Ibu Mintaragen",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    jenis_institusi: "KB",
    rw: "02",
    rt: "03",
    lokasi: "Jl. Sangir No. 8, Mintaragen, Tegal Timur, Kota Tegal",
    deskripsi: "Layanan Kelompok Bermain ramah anak dengan metode belajar kontekstual dan pemantauan status gizi berkala.",
    kontak: "0813-7766-1122",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Pertiwi Mintaragen",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    jenis_institusi: "TK",
    rw: "03",
    rt: "01",
    lokasi: "Jl. Flores No. 25, Mintaragen, Tegal Timur, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Pertiwi berfokus pada kesiapan transisi PAUD ke SD yang menyenangkan tanpa beban tes membaca kaku.",
    kontak: "0856-3344-5566",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.45 WIB",
  },
  {
    nama: "PKBM Tegal Cerdas Mintaragen",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    jenis_institusi: "PKBM",
    rw: "04",
    rt: "02",
    lokasi: "Jl. Halmahera No. 50, Mintaragen, Tegal Timur, Kota Tegal",
    deskripsi: "PKBM penggerak literasi maritim dan kesetaraan pendidikan bagi generasi putus sekolah dan masyarakat pesisir.",
    kontak: "0812-4433-2211",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 15.30 WIB",
  },
  {
    nama: "SPS Teratai Mintaragen",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    jenis_institusi: "SPS",
    rw: "05",
    rt: "04",
    lokasi: "Balai RW 05 Mintaragen, Tegal Timur, Kota Tegal",
    deskripsi: "Satuan PAUD Sejenis terpadu Posyandu Teratai dengan konsultasi parenting dan stimulasi sensori motor.",
    kontak: "0878-3344-6677",
    jadwal: "Rabu dan Sabtu, Pukul 08.30 - 10.30 WIB",
  },

  // Mangkukusuman
  {
    nama: "TK Kristen Mangkukusuman",
    kecamatan: "Tegal Timur",
    kelurahan: "Mangkukusuman",
    jenis_institusi: "TK",
    rw: "01",
    rt: "01",
    lokasi: "Jl. AR. Hakim No. 40, Mangkukusuman, Tegal Timur, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Kristen dengan penanaman nilai kasih, toleransi kebinekaan, kreativitas musik, dan motorik anak.",
    kontak: "0283-353456 / 0813-9900-1122",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "TK Pius Mangkukusuman",
    kecamatan: "Tegal Timur",
    kelurahan: "Mangkukusuman",
    jenis_institusi: "TK",
    rw: "02",
    rt: "03",
    lokasi: "Jl. Kartini No. 19, Mangkukusuman, Tegal Timur, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Katolik berasas karakter humanis, pembentukan watak mandiri, dan lingkungan hijau asri.",
    kontak: "0283-352233",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "KB & PAUD Ceria Mangkukusuman",
    kecamatan: "Tegal Timur",
    kelurahan: "Mangkukusuman",
    jenis_institusi: "KB",
    rw: "03",
    rt: "02",
    lokasi: "Jl. KH. Mansyur No. 14, Mangkukusuman, Tegal Timur, Kota Tegal",
    deskripsi: "Kelompok Bermain aktif interaktif yang merangsang imajinasi dan kemampuan sosio-emosional balita.",
    kontak: "0857-8899-2233",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "SPS Anggrek Asri Mangkukusuman",
    kecamatan: "Tegal Timur",
    kelurahan: "Mangkukusuman",
    jenis_institusi: "SPS",
    rw: "04",
    rt: "01",
    lokasi: "Balai Pertemuan RW 04 Mangkukusuman, Tegal Timur, Kota Tegal",
    deskripsi: "Pojok baca anak dan ruang stimulasi tumbuh kembang balita berbasis keluarga RW 04.",
    kontak: "0812-7788-9900",
    jadwal: "Setiap Hari Selasa Pukul 08.30 - 11.00 WIB",
  },

  // ==========================================
  // 2. KECAMATAN TEGAL BARAT (6 Kelurahan)
  // ==========================================
  // Kraton
  {
    nama: "SPNF SKB Layanan Tegal Barat",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    jenis_institusi: "SKB",
    rw: "01",
    rt: "01",
    lokasi: "Jl. Sawo Barat No. 10, Kraton, Tegal Barat, Kota Tegal",
    deskripsi: "Sentra pembelajaran Sanggar Kegiatan Belajar (SKB) wilayah Tegal Barat untuk Kesetaraan Paket A/B/C, literasi keluarga, dan bimbingan wirausaha.",
    kontak: "0813-7766-5544 (Pengelola SKB Barat)",
    jadwal: "Senin s/d Sabtu, Pukul 08.00 - 15.00 WIB",
  },
  {
    nama: "TK Negeri Pembina Tegal Barat",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    jenis_institusi: "TK",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Sawo Barat No. 8, Kraton, Tegal Barat, Kota Tegal",
    deskripsi: "TK Negeri rujukan Tegal Barat dengan fasilitas bermain luar ruang lengkap, pembelajaran STEAM sederhana, dan pojok UKS ramah anak.",
    kontak: "0283-358765 / 0812-2233-7788",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "KB Harapan Bangsa Kraton",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    jenis_institusi: "KB",
    rw: "02",
    rt: "03",
    lokasi: "Jl. Nanas No. 12, Kraton, Tegal Barat, Kota Tegal",
    deskripsi: "Kelompok bermain dengan konsep fun learning, stimulasi bahasa melalui dongeng, dan motorik kasar aktif.",
    kontak: "0815-9988-3344",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal 2 Kraton",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    jenis_institusi: "TK",
    rw: "03",
    rt: "01",
    lokasi: "Jl. Mangga No. 24, Kraton, Tegal Barat, Kota Tegal",
    deskripsi: "TK Islam berbasis keteladanan dengan bimbingan hafalan surat pendek, doa harian, dan pembiasaan hidup bersih.",
    kontak: "0813-8877-2211",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "PKBM Baruna Kraton Tegal",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    jenis_institusi: "PKBM",
    rw: "04",
    rt: "02",
    lokasi: "Jl. Jambu No. 5, Kraton, Tegal Barat, Kota Tegal",
    deskripsi: "Lembaga PKBM penyelenggara kesetaraan Paket A/B/C, bimbingan literasi digital warga, dan kursus komputer gratis.",
    kontak: "0856-1122-8899",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 15.30 WIB",
  },
  {
    nama: "SPS Cempaka Kraton",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    jenis_institusi: "SPS",
    rw: "05",
    rt: "04",
    lokasi: "Balai RW 05 Kraton, Tegal Barat, Kota Tegal",
    deskripsi: "Pos PAUD terintegrasi BKB dan Posyandu Cempaka untuk deteksi dini pencegahan stunting pada balita.",
    kontak: "0877-4455-6677",
    jadwal: "Hari Kamis Minggu ke-2 & ke-4, Pukul 08.30 - 10.30 WIB",
  },

  // Tegalsari
  {
    nama: "TK Bahari Tegalsari",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    jenis_institusi: "TK",
    rw: "01",
    rt: "01",
    lokasi: "Jl. Blanak No. 17, Tegalsari, Tegal Barat, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak berorientasi kearifan pesisir, edukasi cinta lingkungan laut, dan pembentukan karakter tangguh.",
    kontak: "0813-2244-6688",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.45 WIB",
  },
  {
    nama: "KB Pesisir Ceria Tegalsari",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    jenis_institusi: "KB",
    rw: "02",
    rt: "03",
    lokasi: "Jl. Layur No. 29, Tegalsari, Tegal Barat, Kota Tegal",
    deskripsi: "Kelompok Bermain ramah anak nelayan dengan stimulasi sensori motor dan program makanan bergizi sehat.",
    kontak: "0815-7788-1122",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Pertiwi Tegalsari",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    jenis_institusi: "TK",
    rw: "03",
    rt: "02",
    lokasi: "Jl. Kakap No. 4, Tegalsari, Tegal Barat, Kota Tegal",
    deskripsi: "TK binaan Yayasan Pertiwi dengan pengenalan literasi awal yang menyenangkan dan fasilitas bermain aman.",
    kontak: "0857-1133-5577",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "PKBM Samudra Tegalsari",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    jenis_institusi: "PKBM",
    rw: "04",
    rt: "01",
    lokasi: "Jl. Bandeng No. 11, Tegalsari, Tegal Barat, Kota Tegal",
    deskripsi: "Pusat Kegiatan Belajar Masyarakat penyedia Paket A, B, dan C serta kursus navigasi perkapalan & pengolahan ikan.",
    kontak: "0812-9900-3322",
    jadwal: "Senin s/d Sabtu, Pukul 09.00 - 16.00 WIB",
  },
  {
    nama: "SPS Sedap Malam Tegalsari",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    jenis_institusi: "SPS",
    rw: "05",
    rt: "03",
    lokasi: "Balai RW 05 Tegalsari, Tegal Barat, Kota Tegal",
    deskripsi: "Satuan PAUD Sejenis terintegrasi Posyandu Sedap Malam untuk pemantauan gizi dan stimulasi anak balita.",
    kontak: "0878-6655-4433",
    jadwal: "Selasa dan Jumat, Pukul 08.30 - 10.30 WIB",
  },

  // Kemandungan
  {
    nama: "PAUD & KB Al-Falah Kemandungan",
    kecamatan: "Tegal Barat",
    kelurahan: "Kemandungan",
    jenis_institusi: "KB",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Hang Tuah No. 33, Kemandungan, Tegal Barat, Kota Tegal",
    deskripsi: "Lembaga PAUD Islam dengan stimulasi motorik, pengenalan huruf hijaiyah, dan pendidikan karakter mandiri.",
    kontak: "0813-1122-9988",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Muslimat NU Kemandungan",
    kecamatan: "Tegal Barat",
    kelurahan: "Kemandungan",
    jenis_institusi: "TK",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Ki Gede Sebayu No. 18, Kemandungan, Tegal Barat, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Muslimat NU dengan pembelajaran akhlak, hafalan surat pendek, dan kreasi seni anak.",
    kontak: "0856-4455-7788",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "SPS Melati Kemandungan",
    kecamatan: "Tegal Barat",
    kelurahan: "Kemandungan",
    jenis_institusi: "SPS",
    rw: "03",
    rt: "04",
    lokasi: "Balai Pertemuan RW 03 Kemandungan, Tegal Barat, Kota Tegal",
    deskripsi: "Pos PAUD masyarakat untuk edukasi parenting keluarga dan stimulasi motorik balita.",
    kontak: "0877-1122-3344",
    jadwal: "Setiap Hari Rabu Pukul 08.30 - 10.30 WIB",
  },

  // Pekauman
  {
    nama: "TK Aisyiyah Bustanul Athfal Pekauman",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    jenis_institusi: "TK",
    rw: "01",
    rt: "03",
    lokasi: "Jl. Veteran No. 70, Pekauman, Tegal Barat, Kota Tegal",
    deskripsi: "TK Aisyiyah dengan tradisi mutu pendidikan unggul, tahfidz cilik, dan pengembangan potensi majemuk anak.",
    kontak: "0283-356123 / 0812-3355-7799",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "KB Bintang Kecil Pekauman",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    jenis_institusi: "KB",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Cempaka No. 15, Pekauman, Tegal Barat, Kota Tegal",
    deskripsi: "Kelompok Bermain usia 2-4 tahun dengan metode belajar lewat bermain yang menyenangkan dan aman.",
    kontak: "0815-6655-4433",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "PKBM Karya Mandiri Pekauman",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    jenis_institusi: "PKBM",
    rw: "03",
    rt: "02",
    lokasi: "Jl. Kenanga No. 8, Pekauman, Tegal Barat, Kota Tegal",
    deskripsi: "Pusat Kegiatan Belajar Masyarakat penyedia ujian kesetaraan Paket A/B/C dan pelatihan kewirausahaan UMKM.",
    kontak: "0813-8899-1100",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 16.00 WIB",
  },
  {
    nama: "SPS Flamboyan Pekauman",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    jenis_institusi: "SPS",
    rw: "04",
    rt: "03",
    lokasi: "Balai RW 04 Pekauman, Tegal Barat, Kota Tegal",
    deskripsi: "Layanan stimulasi tumbuh kembang anak usia dini terintegrasi Posyandu Flamboyan Pekauman.",
    kontak: "0878-9988-7766",
    jadwal: "Rabu dan Sabtu, Pukul 08.30 - 10.30 WIB",
  },

  // Muarareja
  {
    nama: "PAUD & KB Bintang Laut Muarareja",
    kecamatan: "Tegal Barat",
    kelurahan: "Muarareja",
    jenis_institusi: "KB",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Pantai Muarareja No. 10, Muarareja, Tegal Barat, Kota Tegal",
    deskripsi: "PAUD pesisir yang mendidik anak-anak kawasan pantai dengan keceriaan, pengenalan ekosistem mangrove, dan literasi dasar.",
    kontak: "0812-7788-3344",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Muarareja Bahari",
    kecamatan: "Tegal Barat",
    kelurahan: "Muarareja",
    jenis_institusi: "TK",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Nelayan No. 25, Muarareja, Tegal Barat, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak dengan ruang kelas terbuka ramah lingkungan dan program pembiasaan pola hidup bersih dan sehat (PHBS).",
    kontak: "0857-3344-9900",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "PKBM Muara Cerdas Tegal Barat",
    kecamatan: "Tegal Barat",
    kelurahan: "Muarareja",
    jenis_institusi: "PKBM",
    rw: "03",
    rt: "03",
    lokasi: "Jl. Muarareja Indah No. 7, Muarareja, Tegal Barat, Kota Tegal",
    deskripsi: "PKBM pemberdayaan masyarakat nelayan dengan program keaksaraan fungsional dan kesetaraan ijazah Paket A/B/C.",
    kontak: "0813-5566-7788",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 15.30 WIB",
  },
  {
    nama: "SPS Mangrove Muarareja",
    kecamatan: "Tegal Barat",
    kelurahan: "Muarareja",
    jenis_institusi: "SPS",
    rw: "04",
    rt: "02",
    lokasi: "Balai RW 04 Muarareja, Tegal Barat, Kota Tegal",
    deskripsi: "Pos PAUD binaan PKK Muarareja dengan fokus pencegahan stunting dan stimulasi sensori anak.",
    kontak: "0877-6655-1122",
    jadwal: "Senin dan Kamis, Pukul 08.30 - 10.30 WIB",
  },

  // Debong Lor
  {
    nama: "PAUD & KB Tunas Harapan Debong Lor",
    kecamatan: "Tegal Barat",
    kelurahan: "Debong Lor",
    jenis_institusi: "KB",
    rw: "01",
    rt: "01",
    lokasi: "Jl. Debong Raya No. 42, Debong Lor, Tegal Barat, Kota Tegal",
    deskripsi: "Layanan kelompok bermain dengan pendekatan saintifik sederhana dan pembentukan kemandirian motorik anak.",
    kontak: "0812-4455-8899",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Pertiwi Debong Lor",
    kecamatan: "Tegal Barat",
    kelurahan: "Debong Lor",
    jenis_institusi: "TK",
    rw: "02",
    rt: "03",
    lokasi: "Jl. Manggis No. 16, Debong Lor, Tegal Barat, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Pertiwi dengan program bermain sambil belajar yang menyenangkan dan ruang kreasi seni anak.",
    kontak: "0856-7788-1122",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.45 WIB",
  },
  {
    nama: "SPS Asoka Debong Lor",
    kecamatan: "Tegal Barat",
    kelurahan: "Debong Lor",
    jenis_institusi: "SPS",
    rw: "03",
    rt: "02",
    lokasi: "Balai RW 03 Debong Lor, Tegal Barat, Kota Tegal",
    deskripsi: "Pos PAUD terpadu Posyandu Asoka untuk pemantauan tumbuh kembang balita RW 03.",
    kontak: "0878-2233-4455",
    jadwal: "Selasa dan Jumat, Pukul 08.30 - 10.30 WIB",
  },

  // ==========================================
  // 3. KECAMATAN TEGAL SELATAN (8 Kelurahan)
  // ==========================================
  // Bandung
  {
    nama: "SPNF SKB Layanan Tegal Selatan",
    kecamatan: "Tegal Selatan",
    kelurahan: "Bandung",
    jenis_institusi: "SKB",
    rw: "01",
    rt: "01",
    lokasi: "Jl. Teuku Umar No. 82, Bandung, Tegal Selatan, Kota Tegal",
    deskripsi: "Sentra pembelajaran Sanggar Kegiatan Belajar (SKB) wilayah Tegal Selatan untuk Kesetaraan Paket A/B/C, literasi vokasi, dan kursus keahlian kerja.",
    kontak: "0815-9988-1122 (Pengelola SKB Selatan)",
    jadwal: "Senin s/d Sabtu, Pukul 08.00 - 15.00 WIB",
  },
  {
    nama: "TK Negeri Pembina Tegal Selatan",
    kecamatan: "Tegal Selatan",
    kelurahan: "Bandung",
    jenis_institusi: "TK",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Teuku Umar No. 80, Bandung, Tegal Selatan, Kota Tegal",
    deskripsi: "TK Negeri Pembina rujukan Tegal Selatan dengan sarana stimulasi holistik, ruang bermain interaktif, dan kebun edukasi anak.",
    kontak: "0283-359988 / 0812-3344-5566",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "PAUD & KB Melati Bandung",
    kecamatan: "Tegal Selatan",
    kelurahan: "Bandung",
    jenis_institusi: "KB",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Bandung Asri No. 14, Bandung, Tegal Selatan, Kota Tegal",
    deskripsi: "Kelompok bermain dengan bimbingan motorik halus, sosialisasi teman sebaya, dan pembiasaan adab.",
    kontak: "0813-8899-7766",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Pertiwi Bandung",
    kecamatan: "Tegal Selatan",
    kelurahan: "Bandung",
    jenis_institusi: "TK",
    rw: "03",
    rt: "04",
    lokasi: "Jl. Raya Bandung No. 22, Bandung, Tegal Selatan, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak dengan penguatan literasi dan numerasi dasar berbasis permainan edukatif.",
    kontak: "0857-2233-4455",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "PKBM Harapan Bangsa Tegal Selatan",
    kecamatan: "Tegal Selatan",
    kelurahan: "Bandung",
    jenis_institusi: "PKBM",
    rw: "04",
    rt: "02",
    lokasi: "Jl. Cik Ditiro No. 45, Bandung, Tegal Selatan, Kota Tegal",
    deskripsi: "Pusat Kegiatan Belajar Masyarakat penyedia program kesetaraan Paket A/B/C dan pelatihan keterampilan menjahit & tata boga.",
    kontak: "0812-9988-4433",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 16.00 WIB",
  },
  {
    nama: "SPS Mawar Bandung",
    kecamatan: "Tegal Selatan",
    kelurahan: "Bandung",
    jenis_institusi: "SPS",
    rw: "05",
    rt: "03",
    lokasi: "Balai RW 05 Bandung, Tegal Selatan, Kota Tegal",
    deskripsi: "Satuan PAUD Sejenis terintegrasi Posyandu Mawar untuk stimulasi balita dan parenting ibu hamil.",
    kontak: "0878-1122-8899",
    jadwal: "Rabu dan Sabtu, Pukul 08.30 - 10.30 WIB",
  },

  // Debong Kulon
  {
    nama: "PAUD & KB Tunas Bangsa Debong Kulon",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kulon",
    jenis_institusi: "KB",
    rw: "01",
    rt: "03",
    lokasi: "Jl. Ki Hajar Dewantara No. 19, Debong Kulon, Tegal Selatan, Kota Tegal",
    deskripsi: "Layanan kelompok bermain dengan penekanan pada kemandirian anak, toilet training, dan pengenalan warna serta angka.",
    kontak: "0813-7766-5544",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Muslimat NU Debong Kulon",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kulon",
    jenis_institusi: "TK",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Kyai Mojo No. 30, Debong Kulon, Tegal Selatan, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak bernuansa religius dengan pembiasaan sholat dhuha cilik, hafalan doa, dan senam ceria.",
    kontak: "0856-9900-1122",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "SPS Teratai Debong Kulon",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kulon",
    jenis_institusi: "SPS",
    rw: "03",
    rt: "02",
    lokasi: "Balai RW 03 Debong Kulon, Tegal Selatan, Kota Tegal",
    deskripsi: "Pos PAUD masyarakat untuk pemantauan stimulasi deteksi dini tumbuh kembang balita.",
    kontak: "0877-4433-2211",
    jadwal: "Selasa dan Kamis, Pukul 08.30 - 10.30 WIB",
  },

  // Debong Tengah
  {
    nama: "TK Al-Ihsan Debong Tengah",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    jenis_institusi: "TK",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Abdul Ghoni No. 12, Debong Tengah, Tegal Selatan, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Islam dengan kurikulum terpadu pembentukan akhlak karimah dan kecerdasan logika.",
    kontak: "0812-6677-8899",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.45 WIB",
  },
  {
    nama: "PAUD & KB Pelangi Debong Tengah",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    jenis_institusi: "KB",
    rw: "02",
    rt: "04",
    lokasi: "Jl. Ki Ageng Tirtayasa No. 8, Debong Tengah, Tegal Selatan, Kota Tegal",
    deskripsi: "Kelompok bermain dengan fasilitas media belajar variatif, permainan balok, dan kreasi melukis.",
    kontak: "0815-3344-7788",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "PKBM Cipta Mandiri Debong Tengah",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    jenis_institusi: "PKBM",
    rw: "03",
    rt: "01",
    lokasi: "Jl. Gatot Subroto No. 55, Debong Tengah, Tegal Selatan, Kota Tegal",
    deskripsi: "Lembaga pendidikan kesetaraan Paket A, B, C dan pelatihan kewirausahaan sablon & kerajinan tangan.",
    kontak: "0813-2211-8899",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 16.00 WIB",
  },
  {
    nama: "SPS Cempaka Debong Tengah",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    jenis_institusi: "SPS",
    rw: "04",
    rt: "03",
    lokasi: "Balai RW 04 Debong Tengah, Tegal Selatan, Kota Tegal",
    deskripsi: "Satuan PAUD Sejenis terpadu Posyandu Cempaka untuk penyuluhan gizi balita dan parenting ayah-bunda.",
    kontak: "0878-5566-3322",
    jadwal: "Senin dan Kamis, Pukul 08.30 - 10.30 WIB",
  },

  // Debong Kidul
  {
    nama: "PAUD & KB Permata Hati Debong Kidul",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kidul",
    jenis_institusi: "KB",
    rw: "01",
    rt: "01",
    lokasi: "Jl. Ki Padmanegara No. 17, Debong Kidul, Tegal Selatan, Kota Tegal",
    deskripsi: "Layanan kelompok bermain yang ramah dan menyenangkan, menstimulasi rasa ingin tahu dan keberanian bersosialisasi.",
    kontak: "0812-8877-4455",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Aisyiyah Debong Kidul",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kidul",
    jenis_institusi: "TK",
    rw: "02",
    rt: "03",
    lokasi: "Jl. Melati Selatan No. 20, Debong Kidul, Tegal Selatan, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Aisyiyah dengan pendidikan karakter Islami, literasi sains sederhana, dan kreasi seni.",
    kontak: "0857-1122-9900",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "SPS Kenanga Debong Kidul",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kidul",
    jenis_institusi: "SPS",
    rw: "03",
    rt: "02",
    lokasi: "Balai RW 03 Debong Kidul, Tegal Selatan, Kota Tegal",
    deskripsi: "Pos PAUD masyarakat untuk pemantauan tumbuh kembang balita RW 03.",
    kontak: "0877-8899-1122",
    jadwal: "Rabu dan Sabtu, Pukul 08.30 - 10.30 WIB",
  },

  // Tunon
  {
    nama: "PAUD & KB Al-Hidayah Tunon",
    kecamatan: "Tegal Selatan",
    kelurahan: "Tunon",
    jenis_institusi: "KB",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Abdul Syukur No. 11, Tunon, Tegal Selatan, Kota Tegal",
    deskripsi: "Layanan PAUD dengan bimbingan membaca iqro dasar, dongeng karakter, dan stimulasi motorik terpadu.",
    kontak: "0813-4433-2211",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Pertiwi Tunon",
    kecamatan: "Tegal Selatan",
    kelurahan: "Tunon",
    jenis_institusi: "TK",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Raya Tunon No. 40, Tunon, Tegal Selatan, Kota Tegal",
    deskripsi: "TK Pertiwi dengan lingkungan belajar nyaman, kebun sekolah mini, dan pembiasaan gotong royong.",
    kontak: "0856-2233-8899",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "SPS Asoka Tunon",
    kecamatan: "Tegal Selatan",
    kelurahan: "Tunon",
    jenis_institusi: "SPS",
    rw: "03",
    rt: "03",
    lokasi: "Balai RW 03 Tunon, Tegal Selatan, Kota Tegal",
    deskripsi: "Pos PAUD terpadu Posyandu Asoka untuk pemantauan tumbuh kembang dan gizi balita.",
    kontak: "0878-3322-1100",
    jadwal: "Selasa dan Jumat, Pukul 08.30 - 10.30 WIB",
  },

  // Kalinyamat Wetan
  {
    nama: "TK Pertiwi Kalinyamat Wetan",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Wetan",
    jenis_institusi: "TK",
    rw: "01",
    rt: "03",
    lokasi: "Jl. Sultan Trenggono No. 15, Kalinyamat Wetan, Tegal Selatan, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak dengan kurikulum penguatan karakter, permainan tradisional edukatif, dan literasi dasar.",
    kontak: "0812-5566-7788",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.45 WIB",
  },
  {
    nama: "PAUD & KB Srikandi Kalinyamat Wetan",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Wetan",
    jenis_institusi: "KB",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Ratu Kalinyamat No. 8, Kalinyamat Wetan, Tegal Selatan, Kota Tegal",
    deskripsi: "Kelompok bermain dengan stimulasi sensori motor, pengenalan bentuk geometri, dan kemandirian anak.",
    kontak: "0815-9900-2233",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "SPS Kamboja Kalinyamat Wetan",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Wetan",
    jenis_institusi: "SPS",
    rw: "03",
    rt: "02",
    lokasi: "Balai RW 03 Kalinyamat Wetan, Tegal Selatan, Kota Tegal",
    deskripsi: "Pos PAUD masyarakat untuk stimulasi deteksi dini tumbuh kembang balita.",
    kontak: "0877-1133-5577",
    jadwal: "Rabu dan Sabtu, Pukul 08.30 - 10.30 WIB",
  },

  // Kalinyamat Kulon
  {
    nama: "PAUD & KB Bina Insan Kalinyamat Kulon",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Kulon",
    jenis_institusi: "KB",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Jepara No. 25, Kalinyamat Kulon, Tegal Selatan, Kota Tegal",
    deskripsi: "Layanan kelompok bermain yang menumbuhkan rasa percaya diri, bahasa ekspresif, dan empati sosial anak.",
    kontak: "0813-8899-3322",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Islam Kalinyamat Kulon",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Kulon",
    jenis_institusi: "TK",
    rw: "02",
    rt: "04",
    lokasi: "Jl. Kudus No. 12, Kalinyamat Kulon, Tegal Selatan, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Islam dengan pembiasaan ibadah praktis, hafalan doa, dan pembelajaran sentra bermain.",
    kontak: "0856-7788-3344",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "PKBM Tunas Cita Kalinyamat Kulon",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Kulon",
    jenis_institusi: "PKBM",
    rw: "03",
    rt: "01",
    lokasi: "Jl. Pati No. 4, Kalinyamat Kulon, Tegal Selatan, Kota Tegal",
    deskripsi: "PKBM penyelenggara pendidikan kesetaraan Paket A/B/C dan pelatihan kerajinan logam & tata busana.",
    kontak: "0812-3322-1100",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 16.00 WIB",
  },
  {
    nama: "SPS Anggrek Kalinyamat Kulon",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Kulon",
    jenis_institusi: "SPS",
    rw: "04",
    rt: "03",
    lokasi: "Balai RW 04 Kalinyamat Kulon, Tegal Selatan, Kota Tegal",
    deskripsi: "Satuan PAUD Sejenis terintegrasi Posyandu Anggrek untuk pemantauan berat badan & tinggi badan balita.",
    kontak: "0878-6677-8899",
    jadwal: "Senin dan Kamis, Pukul 08.30 - 10.30 WIB",
  },

  // Randugunting
  {
    nama: "TK Trisula Randugunting",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    jenis_institusi: "TK",
    rw: "01",
    rt: "03",
    lokasi: "Jl. KS Tubun No. 35, Randugunting, Tegal Selatan, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak berasas pembentukan budi pekerti, kemandirian sosial, dan eksplorasi sains lingkungan.",
    kontak: "0283-357890 / 0812-4455-6677",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "PAUD & KB Insan Kamil Randugunting",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    jenis_institusi: "KB",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Melati No. 19, Randugunting, Tegal Selatan, Kota Tegal",
    deskripsi: "Kelompok bermain Islam terpadu dengan stimulasi holistik integratif dan pendidikan parenting keluarga.",
    kontak: "0813-9900-2211",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal 3 Randugunting",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    jenis_institusi: "TK",
    rw: "03",
    rt: "02",
    lokasi: "Jl. Merpati No. 40, Randugunting, Tegal Selatan, Kota Tegal",
    deskripsi: "TK Aisyiyah dengan pembelajaran sentra, bimbingan tahfidz cilik, dan stimulasi motorik aktif.",
    kontak: "0857-4455-8899",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.45 WIB",
  },
  {
    nama: "PKBM Maju Bersama Randugunting",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    jenis_institusi: "PKBM",
    rw: "04",
    rt: "04",
    lokasi: "Jl. Garuda No. 8, Randugunting, Tegal Selatan, Kota Tegal",
    deskripsi: "Pusat Kegiatan Belajar Masyarakat penyedia program kesetaraan Paket A/B/C dan pelatihan otomotif ringan.",
    kontak: "0812-7766-3322",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 16.00 WIB",
  },
  {
    nama: "SPS Dahlia Randugunting",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    jenis_institusi: "SPS",
    rw: "05",
    rt: "01",
    lokasi: "Balai RW 05 Randugunting, Tegal Selatan, Kota Tegal",
    deskripsi: "Pos PAUD masyarakat untuk deteksi dini tumbuh kembang balita dan penyuluhan gizi seimbang.",
    kontak: "0877-2211-9988",
    jadwal: "Selasa dan Jumat, Pukul 08.30 - 10.30 WIB",
  },

  // ==========================================
  // 4. KECAMATAN MARGADANA (7 Kelurahan)
  // ==========================================
  // Margadana
  {
    nama: "SPNF SKB Layanan Margadana",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    jenis_institusi: "SKB",
    rw: "01",
    rt: "01",
    lokasi: "Jl. Dr. Soetomo No. 18, Margadana, Margadana, Kota Tegal",
    deskripsi: "Sentra pembelajaran Sanggar Kegiatan Belajar (SKB) wilayah Margadana untuk Kesetaraan Paket A/B/C, pemberdayaan masyarakat, dan kursus keterampilan.",
    kontak: "0857-4433-2211 (Pengelola SKB Margadana)",
    jadwal: "Senin s/d Sabtu, Pukul 08.00 - 15.00 WIB",
  },
  {
    nama: "TK Negeri Pembina Margadana",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    jenis_institusi: "TK",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Dr. Soetomo No. 15, Margadana, Margadana, Kota Tegal",
    deskripsi: "TK Negeri Pembina Margadana dengan lingkungan hijau asri, sarana bermain ramah anak, dan kurikulum merdeka belajar.",
    kontak: "0283-341234 / 0812-7788-9900",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "PAUD & KB Kasih Ibu Margadana",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    jenis_institusi: "KB",
    rw: "02",
    rt: "03",
    lokasi: "Jl. Anggrek No. 24, Margadana, Margadana, Kota Tegal",
    deskripsi: "Kelompok bermain binaan TP PKK Margadana yang fokus pada stimulasi motorik, bahasa, dan sosio-emosional anak.",
    kontak: "0856-1122-3344",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Pertiwi Margadana",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    jenis_institusi: "TK",
    rw: "03",
    rt: "01",
    lokasi: "Jl. Melati No. 8, Margadana, Margadana, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak dengan pengenalan literasi-numerasi dini melalui permainan balok dan menyanyi.",
    kontak: "0813-4455-6677",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "PKBM Margadana Mandiri",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    jenis_institusi: "PKBM",
    rw: "04",
    rt: "04",
    lokasi: "Jl. Raya Barat No. 50, Margadana, Margadana, Kota Tegal",
    deskripsi: "Pusat Kegiatan Belajar Masyarakat penyedia program kesetaraan Paket A/B/C dan pelatihan budidaya ikan tawar & jamur.",
    kontak: "0812-3399-8877",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 16.00 WIB",
  },
  {
    nama: "SPS Melati Margadana",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    jenis_institusi: "SPS",
    rw: "05",
    rt: "02",
    lokasi: "Balai RW 05 Margadana, Margadana, Kota Tegal",
    deskripsi: "Pos PAUD terpadu Posyandu Melati untuk stimulasi dini balita dan edukasi MPASI sehat.",
    kontak: "0878-1122-4455",
    jadwal: "Rabu dan Sabtu, Pukul 08.30 - 10.30 WIB",
  },

  // Kaligangsa
  {
    nama: "TK Aisyiyah Bustanul Athfal Kaligangsa",
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    jenis_institusi: "TK",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Raya Kaligangsa No. 88, Kaligangsa, Margadana, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Aisyiyah dengan pembiasaan nilai Islami, hafalan surat pendek, dan kreasi motorik halus.",
    kontak: "0813-8877-1122",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.45 WIB",
  },
  {
    nama: "PAUD & KB An-Nur Kaligangsa",
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    jenis_institusi: "KB",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Masjid Kaligangsa No. 12, Kaligangsa, Margadana, Kota Tegal",
    deskripsi: "Kelompok bermain usia 2-4 tahun dengan metode belajar lewat bermain yang menyenangkan dan penuh kasih.",
    kontak: "0857-3322-1144",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "PKBM Kaligangsa Jaya",
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    jenis_institusi: "PKBM",
    rw: "03",
    rt: "03",
    lokasi: "Jl. Kali Asri No. 5, Kaligangsa, Margadana, Kota Tegal",
    deskripsi: "PKBM penggerak kesetaraan Paket A, B, C dan pelatihan pengolahan hasil pertanian & kerajinan tangan.",
    kontak: "0812-4455-1199",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 15.30 WIB",
  },
  {
    nama: "SPS Mawar Kaligangsa",
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    jenis_institusi: "SPS",
    rw: "04",
    rt: "02",
    lokasi: "Balai RW 04 Kaligangsa, Margadana, Kota Tegal",
    deskripsi: "Pos PAUD masyarakat untuk pemantauan tumbuh kembang dan gizi balita RW 04.",
    kontak: "0877-6655-3322",
    jadwal: "Selasa dan Jumat, Pukul 08.30 - 10.30 WIB",
  },

  // Cabawan
  {
    nama: "PAUD & KB Tunas Harapan Cabawan",
    kecamatan: "Margadana",
    kelurahan: "Cabawan",
    jenis_institusi: "KB",
    rw: "01",
    rt: "01",
    lokasi: "Jl. Cabawan Raya No. 20, Cabawan, Margadana, Kota Tegal",
    deskripsi: "Layanan kelompok bermain dengan penekanan pada sosialisasi anak, kemandirian motorik, dan literasi bercerita.",
    kontak: "0813-2233-8877",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Pertiwi Cabawan",
    kecamatan: "Margadana",
    kelurahan: "Cabawan",
    jenis_institusi: "TK",
    rw: "02",
    rt: "03",
    lokasi: "Jl. Dahlia No. 14, Cabawan, Margadana, Kota Tegal",
    deskripsi: "TK binaan Yayasan Pertiwi dengan kegiatan bermain di luar ruang, pengenalan sains sederhana, dan kesenian anak.",
    kontak: "0856-4455-6677",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "SPS Kamboja Cabawan",
    kecamatan: "Margadana",
    kelurahan: "Cabawan",
    jenis_institusi: "SPS",
    rw: "03",
    rt: "02",
    lokasi: "Balai RW 03 Cabawan, Margadana, Kota Tegal",
    deskripsi: "Pos PAUD terpadu Posyandu Kamboja untuk pemantauan tumbuh kembang anak balita.",
    kontak: "0878-9900-2211",
    jadwal: "Senin dan Kamis, Pukul 08.30 - 10.30 WIB",
  },

  // Krandon
  {
    nama: "PAUD & KB Bina Mandiri Krandon",
    kecamatan: "Margadana",
    kelurahan: "Krandon",
    jenis_institusi: "KB",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Krandon Indah No. 16, Krandon, Margadana, Kota Tegal",
    deskripsi: "Kelompok bermain dengan media edukatif kreatif, stimulasi sensori motorik, dan pembiasaan hidup sehat.",
    kontak: "0812-8877-3344",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Muslimat NU Krandon",
    kecamatan: "Margadana",
    kelurahan: "Krandon",
    jenis_institusi: "TK",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Kyai Krandon No. 28, Krandon, Margadana, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Muslimat NU dengan kurikulum Islami, bimbingan doa harian, dan pembinaan budi pekerti.",
    kontak: "0857-1122-3344",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "SPS Kenanga Krandon",
    kecamatan: "Margadana",
    kelurahan: "Krandon",
    jenis_institusi: "SPS",
    rw: "03",
    rt: "03",
    lokasi: "Balai RW 03 Krandon, Margadana, Kota Tegal",
    deskripsi: "Pos PAUD masyarakat terintegrasi Posyandu Kenanga untuk pencegahan stunting dan stimulasi balita.",
    kontak: "0877-4455-8899",
    jadwal: "Rabu dan Sabtu, Pukul 08.30 - 10.30 WIB",
  },

  // Pesurungan Kidul
  {
    nama: "PAUD & KB Permata Bunda Pesurungan Kidul",
    kecamatan: "Margadana",
    kelurahan: "Pesurungan Kidul",
    jenis_institusi: "KB",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Ki Gede Pesurungan No. 35, Pesurungan Kidul, Margadana, Kota Tegal",
    deskripsi: "Layanan kelompok bermain yang hangat dan ramah anak, mengembangkan kemampuan bahasa dan motorik balita.",
    kontak: "0813-4455-2211",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Pertiwi Pesurungan Kidul",
    kecamatan: "Margadana",
    kelurahan: "Pesurungan Kidul",
    jenis_institusi: "TK",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Kenari No. 12, Pesurungan Kidul, Margadana, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak dengan kurikulum bermain bermakna dan pembentukan rasa percaya diri anak usia dini.",
    kontak: "0856-7788-9911",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "SPS Teratai Pesurungan Kidul",
    kecamatan: "Margadana",
    kelurahan: "Pesurungan Kidul",
    jenis_institusi: "SPS",
    rw: "03",
    rt: "04",
    lokasi: "Balai RW 03 Pesurungan Kidul, Margadana, Kota Tegal",
    deskripsi: "Pos PAUD masyarakat untuk deteksi dini tumbuh kembang balita.",
    kontak: "0878-2233-1144",
    jadwal: "Selasa dan Jumat, Pukul 08.30 - 10.30 WIB",
  },

  // Pesurungan Lor
  {
    nama: "PAUD & KB Bintang Kecil Pesurungan Lor",
    kecamatan: "Margadana",
    kelurahan: "Pesurungan Lor",
    jenis_institusi: "KB",
    rw: "01",
    rt: "01",
    lokasi: "Jl. Sawo Lor No. 18, Pesurungan Lor, Margadana, Kota Tegal",
    deskripsi: "Kelompok bermain dengan media belajar eksploratif, motorik aktif, dan pengenalan literasi dasar.",
    kontak: "0812-7766-8899",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal Pesurungan Lor",
    kecamatan: "Margadana",
    kelurahan: "Pesurungan Lor",
    jenis_institusi: "TK",
    rw: "02",
    rt: "03",
    lokasi: "Jl. Melati Utara No. 22, Pesurungan Lor, Margadana, Kota Tegal",
    deskripsi: "TK Islam Aisyiyah dengan pembiasaan adab harian, hafalan surat juz 30, dan kreasi seni anak.",
    kontak: "0857-3344-7788",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 10.30 WIB",
  },
  {
    nama: "SPS Dahlia Pesurungan Lor",
    kecamatan: "Margadana",
    kelurahan: "Pesurungan Lor",
    jenis_institusi: "SPS",
    rw: "03",
    rt: "02",
    lokasi: "Balai RW 03 Pesurungan Lor, Margadana, Kota Tegal",
    deskripsi: "Satuan PAUD Sejenis terintegrasi Posyandu Dahlia untuk stimulasi gizi dan tumbuh kembang balita.",
    kontak: "0877-8899-3322",
    jadwal: "Rabu dan Sabtu, Pukul 08.30 - 10.30 WIB",
  },

  // Sumurpanggang
  {
    nama: "TK Pertiwi Sumurpanggang",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    jenis_institusi: "TK",
    rw: "01",
    rt: "02",
    lokasi: "Jl. Raya Sumurpanggang No. 45, Sumurpanggang, Margadana, Kota Tegal",
    deskripsi: "Taman Kanak-Kanak Pertiwi dengan arena bermain luas, stimulasi motorik terarah, dan pembelajaran karakter.",
    kontak: "0283-343210 / 0812-3344-8899",
    jadwal: "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
  },
  {
    nama: "PAUD & KB Tunas Bangsa Sumurpanggang",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    jenis_institusi: "KB",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Cempaka No. 10, Sumurpanggang, Margadana, Kota Tegal",
    deskripsi: "Kelompok bermain dengan konsep belajar gembira, pengenalan warna, bentuk, dan sosialisasi anak.",
    kontak: "0815-4455-9900",
    jadwal: "Senin s/d Kamis, Pukul 08.00 - 10.30 WIB",
  },
  {
    nama: "PKBM Bina Warga Panggang",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    jenis_institusi: "PKBM",
    rw: "03",
    rt: "03",
    lokasi: "Jl. Lapangan Panggang No. 7, Sumurpanggang, Margadana, Kota Tegal",
    deskripsi: "Pusat Kegiatan Belajar Masyarakat penyedia ujian kesetaraan Paket A/B/C dan pelatihan tata busana & komputer.",
    kontak: "0813-8899-4455",
    jadwal: "Senin s/d Sabtu, Pukul 08.30 - 16.00 WIB",
  },
  {
    nama: "SPS Cempaka Sumurpanggang",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    jenis_institusi: "SPS",
    rw: "04",
    rt: "02",
    lokasi: "Balai RW 04 Sumurpanggang, Margadana, Kota Tegal",
    deskripsi: "Pos PAUD masyarakat terintegrasi Posyandu Cempaka untuk pemantauan tumbuh kembang dan gizi balita.",
    kontak: "0878-1133-7788",
    jadwal: "Senin dan Kamis, Pukul 08.30 - 10.30 WIB",
  },
];

/**
 * Generator Master Seed Item untuk seluruh Satuan PAUD & PKBM Kota Tegal
 */
export function buildPaudMasterSeed(): MasterKomunitasSeedItem[] {
  return RAW_PAUD_PKBM_TEGAL.map((item, index) => {
    const kecSlug = slugify(item.kecamatan);
    const kelSlug = slugify(item.kelurahan);
    const nameSlug = slugify(item.nama);
    const id = `kom-paud-${kecSlug}-${kelSlug}-${nameSlug}`;
    const rw = (item.rw || `0${(index % 6) + 1}`).padStart(2, "0");
    const rt = (item.rt || `0${(index % 4) + 1}`).padStart(2, "0");

    return {
      id,
      nama: `${item.nama}, ${item.kelurahan}, ${item.kecamatan}, Kota Tegal`,
      jenis: "satuan_paud",
      kecamatan: item.kecamatan,
      kelurahan: item.kelurahan,
      rt,
      rw,
      lokasi:
        item.lokasi ||
        `Gedung ${item.nama}, Kel. ${item.kelurahan}, Kec. ${item.kecamatan}, Kota Tegal`,
      deskripsi:
        item.deskripsi ||
        `Lembaga PAUD & Pendidikan Kesetaraan (${item.nama}) menyelenggarakan layanan stimulasi tumbuh kembang anak usia dini, kesiapan belajar, pendidikan nonformal kesetaraan, dan parenting keluarga.`,
      kontak: item.kontak || `0813-5566-${String(2000 + index).padStart(4, "0")} (Pengelola)`,
      jadwal: item.jadwal || "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB",
    };
  });
}

export const SEED_PAUD_PKBM_TEGAL: MasterKomunitasSeedItem[] = buildPaudMasterSeed();
