import type { MasterKomunitasSeedItem } from "./tegal-data";

function slugify(text: string): string {
  return (text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export interface RawPaudItem {
  nama: string;
  npsn?: string;
  kecamatan: string;
  kelurahan: string;
  jenis_institusi?: "TK" | "KB" | "RA" | "SPS" | "TPA" | "PKBM" | "SKB";
  rt?: string;
  rw?: string;
  jadwal?: string;
  kontak?: string;
  lokasi?: string;
  deskripsi?: string;
}

// Data Lengkap Resmi 219 Satuan PAUD (TK, KB, RA, SPS, TPA), PKBM, dan SKB se-Kota Tegal
export const RAW_PAUD_PKBM_TEGAL: RawPaudItem[] = [
  // ==========================================
  // KECAMATAN TEGAL TIMUR
  // ==========================================
  // Mintaragen (6 Lembaga)
  {
    nama: "RA Usamah 2",
    npsn: "69977271",
    jenis_institusi: "RA",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    lokasi: "Jl. Waringin Gg. 9, Mintaragen, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Ihsaniyah 1",
    npsn: "69818093",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    lokasi: "Mintaragen, Tegal Timur, Kota Tegal",
  },
  {
    nama: "Pos PAUD Kenanga Mintaragen",
    npsn: "69916493",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    lokasi: "Mintaragen, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal VII",
    npsn: "20351619",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    lokasi: "Mintaragen, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Al Hidayah 1",
    npsn: "20351635",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    lokasi: "Mintaragen, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Ihsaniyah 1",
    npsn: "20351656",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    lokasi: "Mintaragen, Tegal Timur, Kota Tegal",
  },
  // Panggung (33 Lembaga)
  {
    nama: "RA Sakila Kerti",
    npsn: "69884926",
    jenis_institusi: "RA",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    rw: "04",
    rt: "04",
    lokasi: "Jl. Kaligung Gang III No. 32 RT 04/RW IV, Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "RA Syuhada",
    npsn: "69884927",
    jenis_institusi: "RA",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    rw: "11",
    rt: "05",
    lokasi: "Jl. Adonara 2 RT 05/RW XI, Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "RA Syiarul Islam",
    npsn: "69743506",
    jenis_institusi: "RA",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Jl. KH. Muklas No. 7, Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "RA Usamah",
    npsn: "69743507",
    jenis_institusi: "RA",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    rw: "14",
    rt: "01",
    lokasi: "Jl. Surabayan RT 01/RW 14, Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Aisyiyah Anak Sholeh",
    npsn: "69928754",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Amalia",
    npsn: "69935790",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Bina Anak Sholeh (BIAS)",
    npsn: "69928753",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Ihsaniyah 3",
    npsn: "69818091",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Prima Universal",
    npsn: "69818044",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Sakila Kerti",
    npsn: "69818046",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Kompleks Terminal Bus Tegal, Jl. Kolonel Sugiono, Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Syi'arul Islam",
    npsn: "69818052",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Syuhada",
    npsn: "69914221",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Sekar Melati",
    npsn: "69818049",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KBI Usamah",
    npsn: "69818055",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "PAUD TPQ Nurul Huda",
    npsn: "69818110",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "PKBM Citra Mandiri",
    npsn: "P9959971",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "PKBM Sakila Kerti",
    npsn: "P9970024",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Kompleks Terminal Bus & Pesisir, Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "Pos PAUD Anyelir",
    npsn: "69928757",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "Pos PAUD Nusa Indah",
    npsn: "69818102",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "Pos PAUD Seruni Panggung",
    npsn: "69818105",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah BA IX",
    npsn: "20351620",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal IV",
    npsn: "20351617",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal VI",
    npsn: "20351618",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal XII",
    npsn: "20351621",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Ihsaniyah III",
    npsn: "20351623",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Islam Ash Sholihin",
    npsn: "20360028",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Kartika III-28",
    npsn: "20360029",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Masyithoh VI",
    npsn: "20351627",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Negeri Pembina Tegal Timur",
    npsn: "20351677",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.6 Panggung",
    npsn: "20351629",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Jl. Veteran No. 12, Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK PGRI",
    npsn: "20351633",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Syiarul Islam",
    npsn: "70061973",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TPA Usamah",
    npsn: "69966219",
    jenis_institusi: "TPA",
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    lokasi: "Panggung, Tegal Timur, Kota Tegal",
  },
  // Slerok (19 Lembaga)
  {
    nama: "RA Al Hasaniyah",
    npsn: "69743503",
    jenis_institusi: "RA",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Jl. Werkudoro No. 24, Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "RA Istiqomah",
    npsn: "69743504",
    jenis_institusi: "RA",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Jl. Gatotkaca No. 12, Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "RA Miftahussalam",
    npsn: "69743501",
    jenis_institusi: "RA",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Jl. Antasena No. 16, Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Darul Kifaah",
    npsn: "69935822",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Istiqomah",
    npsn: "69818040",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Nurunnisa",
    npsn: "69818042",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Permata Hati",
    npsn: "69818070",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Riyaadul Jannah",
    npsn: "69918019",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Transisi Anilo",
    npsn: "70063185",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Tarbiyatul Khasanah",
    npsn: "69818057",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "PAUD TPQ Ath Thohiriyah",
    npsn: "69818109",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "PKBM Sarana Maju",
    npsn: "P2970158",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "PKBM Transisi Anilo",
    npsn: "P2971356",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "Pos PAUD Kartini RW. VI",
    npsn: "69917972",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    rw: "06",
    lokasi: "Balai RW 06 Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "Pos PAUD Sumbodro",
    npsn: "69914181",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "Pos PAUD Werkudoro",
    npsn: "69818058",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Masyithoh VIII",
    npsn: "20351072",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Nurunnisa",
    npsn: "70029822",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.3 Slerok",
    npsn: "20351634",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    lokasi: "Slerok, Tegal Timur, Kota Tegal",
  },
  // Kejambon (17 Lembaga)
  {
    nama: "RA Permata Hati",
    npsn: "69743502",
    jenis_institusi: "RA",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Jl. Nakula Gg. Widuri No. 27, Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "RA Perwanida",
    npsn: "69743505",
    jenis_institusi: "RA",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Jl. Baladewa No. 5, Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Aisyiyah Kejambon",
    npsn: "69818059",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Ananda Mandiri",
    npsn: "69973495",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "KB Nurullah",
    npsn: "69916865",
    jenis_institusi: "KB",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "Pos PAUD Al Maemunah",
    npsn: "69914120",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "Pos PAUD Sekar Kamboja",
    npsn: "69914193",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal III",
    npsn: "20351615",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal V",
    npsn: "20351616",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal XI",
    npsn: "20359988",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Cendrawasih",
    npsn: "20351631",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Masyithoh II",
    npsn: "20351624",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Masyithoh IV",
    npsn: "20351626",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Permata Ibu",
    npsn: "20351636",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.13 Kejambon",
    npsn: "20351632",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TPA Aisyiyah Kejambon",
    npsn: "69818075",
    jenis_institusi: "TPA",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TPA Ananda Mandiri",
    npsn: "69973493",
    jenis_institusi: "TPA",
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    lokasi: "Kejambon, Tegal Timur, Kota Tegal",
  },
  // Mangkukusuman (4 Lembaga)
  {
    nama: "PKBM Star of Tomorrow",
    npsn: "P9962931",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Timur",
    kelurahan: "Mangkukusuman",
    lokasi: "Mangkukusuman, Tegal Timur, Kota Tegal",
  },
  {
    nama: "Pos PAUD Cermai",
    npsn: "70034979",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Timur",
    kelurahan: "Mangkukusuman",
    lokasi: "Mangkukusuman, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal I",
    npsn: "20359984",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Mangkukusuman",
    lokasi: "Mangkukusuman, Tegal Timur, Kota Tegal",
  },
  {
    nama: "TK Masyithoh III",
    npsn: "20351625",
    jenis_institusi: "TK",
    kecamatan: "Tegal Timur",
    kelurahan: "Mangkukusuman",
    lokasi: "Mangkukusuman, Tegal Timur, Kota Tegal",
  },
  // ==========================================
  // KECAMATAN TEGAL BARAT
  // ==========================================
  // Pekauman (18 Lembaga)
  {
    nama: "RA At Taqwa",
    npsn: "69743498",
    jenis_institusi: "RA",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Jl. Kelapa Sawit No. 3, Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Al-Irsyad",
    npsn: "69818043",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB At-Taqwa",
    npsn: "69818061",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Azzurofah",
    npsn: "69818065",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Elfath Kids",
    npsn: "69918017",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Homeschooling ABC D",
    npsn: "69818053",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Kiddy Care",
    npsn: "69952478",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "PKBM Bina Harapan",
    npsn: "P9959947",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "PKBM Budi Luhur",
    npsn: "P9908267",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "PKBM Mutiara Shahabat",
    npsn: "P9959948",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Delima",
    npsn: "69818097",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Al-Irsyad Al-Islamiyah",
    npsn: "20351661",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Bagya Wacana",
    npsn: "20351657",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Hang Tuah 16",
    npsn: "20351660",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Islam Azzurofah",
    npsn: "20360021",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Kiddy Care",
    npsn: "20362364",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Negeri Pembina Kota Tegal",
    npsn: "20351671",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.7 Pekauman",
    npsn: "20351664",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    lokasi: "Pekauman, Tegal Barat, Kota Tegal",
  },
  // Kemandungan (6 Lembaga)
  {
    nama: "KB Bina Anak Sholeh (BIAS)",
    npsn: "69818088",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Kemandungan",
    lokasi: "Kemandungan, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Global Inbyra School",
    npsn: "69960275",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Kemandungan",
    lokasi: "Kemandungan, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Mutiara Shahabat",
    npsn: "69964731",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Kemandungan",
    lokasi: "Kemandungan, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Kenanga Kemandungan",
    npsn: "69818099",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Kemandungan",
    lokasi: "Kemandungan, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Global Inbyra School",
    npsn: "69960276",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Kemandungan",
    lokasi: "Kemandungan, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.2 Kemandungan",
    npsn: "20360041",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Kemandungan",
    lokasi: "Kemandungan, Tegal Barat, Kota Tegal",
  },
  // Kraton (15 Lembaga)
  {
    nama: "KB Elkana",
    npsn: "69818045",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Pelita Harapan Bangsa",
    npsn: "69952479",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Pius",
    npsn: "69818092",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Aisyiyah Tegal Barat",
    npsn: "69818081",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Dewi Sartika Kraton",
    npsn: "69963107",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Kartini",
    npsn: "69818094",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Kenanga Kraton",
    npsn: "69916882",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal VIII",
    npsn: "20360241",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Al Khairiyyah",
    npsn: "20351667",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Assyifa",
    npsn: "20351669",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Elkana",
    npsn: "20351658",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Little Star",
    npsn: "20351674",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.5 Kraton",
    npsn: "20351662",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Pius",
    npsn: "20351655",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  {
    nama: "UPTD SPNF Sanggar Kegiatan Belajar Kota Tegal",
    npsn: "P9959977",
    jenis_institusi: "SKB",
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    lokasi: "Kraton, Tegal Barat, Kota Tegal",
  },
  // Tegalsari (14 Lembaga)
  {
    nama: "KB Insan Mandiri",
    npsn: "70051182",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Kalimasada",
    npsn: "70061151",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Little Star",
    npsn: "69818056",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Tunas Hidup Harapan Kita",
    npsn: "69932227",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "PKBM Maju Bersama",
    npsn: "P9908268",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Bougenville Tegalsari",
    npsn: "69818101",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Mawar Merah",
    npsn: "69914231",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Melati Sari",
    npsn: "69917977",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Sekar Melati",
    npsn: "69818103",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Persatuan Ummat Islam (PUI) Cabang Tegal",
    npsn: "20351668",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.4 Tegalsari",
    npsn: "20351663",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Shining Little Star",
    npsn: "69818060",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Tunas Hidup Harapan Kita",
    npsn: "20351672",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Tut Wuri",
    npsn: "20351665",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    lokasi: "Tegalsari, Tegal Barat, Kota Tegal",
  },
  // Pesurungan Kidul (7 Lembaga)
  {
    nama: "KB Islam Al Azhar 66 Kota Tegal",
    npsn: "70054968",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Pesurungan Kidul",
    lokasi: "Pesurungan Kidul, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Mekar",
    npsn: "69975546",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Pesurungan Kidul",
    lokasi: "Pesurungan Kidul, Tegal Barat, Kota Tegal",
  },
  {
    nama: "KB Sofa Marwah",
    npsn: "69818087",
    jenis_institusi: "KB",
    kecamatan: "Tegal Barat",
    kelurahan: "Pesurungan Kidul",
    lokasi: "Pesurungan Kidul, Tegal Barat, Kota Tegal",
  },
  {
    nama: "PKBM Mekar",
    npsn: "P9970191",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Barat",
    kelurahan: "Pesurungan Kidul",
    lokasi: "Pesurungan Kidul, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Melati Pesurungan Kidul",
    npsn: "69915297",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Pesurungan Kidul",
    lokasi: "Pesurungan Kidul, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Islam Al Azhar 66 Kota Tegal",
    npsn: "70052713",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Pesurungan Kidul",
    lokasi: "Pesurungan Kidul, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.8 Pesurungan Kidul",
    npsn: "20351659",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Pesurungan Kidul",
    lokasi: "Pesurungan Kidul, Tegal Barat, Kota Tegal",
  },
  // Muarareja (3 Lembaga)
  {
    nama: "PAUD TPQ Plus Insan Kamil",
    npsn: "69990458",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Muarareja",
    lokasi: "Muarareja, Tegal Barat, Kota Tegal",
  },
  {
    nama: "Pos PAUD Mawar",
    npsn: "69968166",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Muarareja",
    lokasi: "Muarareja, Tegal Barat, Kota Tegal",
  },
  {
    nama: "TK Nurul Huda",
    npsn: "20351670",
    jenis_institusi: "TK",
    kecamatan: "Tegal Barat",
    kelurahan: "Muarareja",
    lokasi: "Muarareja, Tegal Barat, Kota Tegal",
  },
  // Debong Lor (1 Lembaga)
  {
    nama: "Pos PAUD Seruni Debong Lor",
    npsn: "69917960",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Barat",
    kelurahan: "Debong Lor",
    lokasi: "Debong Lor, Tegal Barat, Kota Tegal",
  },
  // ==========================================
  // KECAMATAN TEGAL SELATAN
  // ==========================================
  // Randugunting (18 Lembaga)
  {
    nama: "RA Hidayatul Mubtadiien",
    npsn: "69958134",
    jenis_institusi: "RA",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    rw: "02",
    rt: "07",
    lokasi: "Jl. Merpati Gg. Kaswari RT 07/RW 02, Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "RA BIAS Assalam",
    npsn: "69743500",
    jenis_institusi: "RA",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Jl. Dadali No. 12, Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "KB Bias Assalam",
    npsn: "69818068",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "KB Hidayatul Mubtadi-ien",
    npsn: "69917032",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "KB Pelita Hati",
    npsn: "69818090",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "KB Primagama Islami",
    npsn: "69818083",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "KB Raudlotul Jannah",
    npsn: "69818051",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "KB Tunas Harapan Bangsa",
    npsn: "69818047",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "Pos PAUD Tunas Harapan Randugunting",
    npsn: "69818071",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "SPS PAUD TPQ Tahfidz Cahaya Quran",
    npsn: "70038525",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal II",
    npsn: "20350569",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Al Hidayah II",
    npsn: "20350982",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Masyithoh 1",
    npsn: "20350565",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Nurus Sunnah",
    npsn: "70060478",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Pelita Hati",
    npsn: "20350985",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.1 Randugunting",
    npsn: "20350563",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Primagama Islami",
    npsn: "69969650",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TPA Bias Assalam",
    npsn: "69965296",
    jenis_institusi: "TPA",
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    lokasi: "Randugunting, Tegal Selatan, Kota Tegal",
  },
  // Tunon (3 Lembaga)
  {
    nama: "RA Baitush Shobirin",
    npsn: "69743499",
    jenis_institusi: "RA",
    kecamatan: "Tegal Selatan",
    kelurahan: "Tunon",
    rw: "02",
    rt: "01",
    lokasi: "Jl. Nyi Ageng Serang RT 01/RW 02, Tunon, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "Pos PAUD Tunas Mutiara",
    npsn: "69818054",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Tunon",
    lokasi: "Tunon, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Masyithoh V",
    npsn: "20350568",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Tunon",
    lokasi: "Tunon, Tegal Selatan, Kota Tegal",
  },
  // Debong Tengah (8 Lembaga)
  {
    nama: "KB Aisyiyah Baitul Karim",
    npsn: "69966352",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    lokasi: "Debong Tengah, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "KB Qurrota A'yun",
    npsn: "69818048",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    lokasi: "Debong Tengah, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "PAUD TPQ Al-Mukhlishin",
    npsn: "69818080",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    lokasi: "Debong Tengah, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "Pos PAUD Bianglala",
    npsn: "70034057",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    lokasi: "Debong Tengah, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Al Khidmah",
    npsn: "69969648",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    lokasi: "Debong Tengah, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Baiturrokhman",
    npsn: "20350986",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    lokasi: "Debong Tengah, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Kemala Bhayangkari 25",
    npsn: "20350984",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    lokasi: "Debong Tengah, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.10 Debong Tengah",
    npsn: "20360039",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    lokasi: "Debong Tengah, Tegal Selatan, Kota Tegal",
  },
  // Debong Kidul (3 Lembaga)
  {
    nama: "KB Debong Kidul",
    npsn: "69918013",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kidul",
    lokasi: "Debong Kidul, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "PKBM Arum Indah",
    npsn: "P9962828",
    jenis_institusi: "PKBM",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kidul",
    lokasi: "Debong Kidul, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "Pos PAUD Mekar Sari",
    npsn: "69818064",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kidul",
    lokasi: "Debong Kidul, Tegal Selatan, Kota Tegal",
  },
  // Kalinyamat Wetan (3 Lembaga)
  {
    nama: "KB Jaya Lestari",
    npsn: "69917247",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Wetan",
    lokasi: "Kalinyamat Wetan, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "Pos PAUD Balita Jaya",
    npsn: "69917226",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Wetan",
    lokasi: "Kalinyamat Wetan, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Al Quran Al Haromain",
    npsn: "70027338",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Wetan",
    lokasi: "Kalinyamat Wetan, Tegal Selatan, Kota Tegal",
  },
  // Keturen (2 Lembaga)
  {
    nama: "KB Sekar Kemuning",
    npsn: "69818050",
    jenis_institusi: "KB",
    kecamatan: "Tegal Selatan",
    kelurahan: "Keturen",
    lokasi: "Keturen, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Negeri Pembina Tegal Selatan",
    npsn: "69966113",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Keturen",
    lokasi: "Keturen, Tegal Selatan, Kota Tegal",
  },
  // Kalinyamat Kulon (3 Lembaga)
  {
    nama: "PAUD TPQ Al-Hikmah",
    npsn: "69818111",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Kulon",
    lokasi: "Kalinyamat Kulon, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "Pos PAUD Melati Kalinyamat Kulon",
    npsn: "69914225",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Kulon",
    lokasi: "Kalinyamat Kulon, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.12 Kalinyamat Kulon",
    npsn: "20351683",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Kulon",
    lokasi: "Kalinyamat Kulon, Tegal Selatan, Kota Tegal",
  },
  // Debong Kulon (2 Lembaga)
  {
    nama: "Pos PAUD Dewi Sartika Debong Kulon",
    npsn: "69818041",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kulon",
    lokasi: "Debong Kulon, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Darunnajah",
    npsn: "20350983",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kulon",
    lokasi: "Debong Kulon, Tegal Selatan, Kota Tegal",
  },
  // Bandung (3 Lembaga)
  {
    nama: "Pos PAUD Sejahtera",
    npsn: "70034724",
    jenis_institusi: "SPS",
    kecamatan: "Tegal Selatan",
    kelurahan: "Bandung",
    lokasi: "Bandung, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal XIII",
    npsn: "20350885",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Bandung",
    lokasi: "Bandung, Tegal Selatan, Kota Tegal",
  },
  {
    nama: "TK Pertiwi 25.9 Bandung",
    npsn: "20348592",
    jenis_institusi: "TK",
    kecamatan: "Tegal Selatan",
    kelurahan: "Bandung",
    lokasi: "Bandung, Tegal Selatan, Kota Tegal",
  },
  // ==========================================
  // KECAMATAN MARGADANA
  // ==========================================
  // Margadana (9 Lembaga)
  {
    nama: "RA Al Furqon",
    npsn: "69977270",
    jenis_institusi: "RA",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    rw: "10",
    rt: "05",
    lokasi: "Jl. Prof Buya Hamka No. 75 RT 05/RW 10, Margadana, Kota Tegal",
  },
  {
    nama: "KB Minat",
    npsn: "69818079",
    jenis_institusi: "KB",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    lokasi: "Margadana, Kota Tegal",
  },
  {
    nama: "KB Pelita Bangsa",
    npsn: "69818084",
    jenis_institusi: "KB",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    lokasi: "Margadana, Kota Tegal",
  },
  {
    nama: "KB Rumah Bintang",
    npsn: "69914290",
    jenis_institusi: "KB",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    lokasi: "Margadana, Kota Tegal",
  },
  {
    nama: "PAUD TPQ Al-Munawwaroh",
    npsn: "69818098",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    lokasi: "Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Anggrek Bulan",
    npsn: "69914169",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    lokasi: "Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Bougenville Margadana",
    npsn: "69914267",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    lokasi: "Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Kesambi Sari",
    npsn: "69906837",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    lokasi: "Margadana, Kota Tegal",
  },
  {
    nama: "TK Negeri Pembina Kecamatan Margadana",
    npsn: "20351684",
    jenis_institusi: "TK",
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    lokasi: "Margadana, Kota Tegal",
  },
  // Kaligangsa (6 Lembaga)
  {
    nama: "RA Al-Izzah",
    npsn: "69743496",
    jenis_institusi: "RA",
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    lokasi: "Jl. M. Thoha No. 1, Kaligangsa, Margadana, Kota Tegal",
  },
  {
    nama: "RA Miftahun Najah",
    npsn: "69743495",
    jenis_institusi: "RA",
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    lokasi: "Jl. Bekasi No. 80, Kaligangsa, Margadana, Kota Tegal",
  },
  {
    nama: "KB Al-Izzah",
    npsn: "69818073",
    jenis_institusi: "KB",
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    lokasi: "Kaligangsa, Margadana, Kota Tegal",
  },
  {
    nama: "PAUD TPQ Al-Izzah",
    npsn: "69818095",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    lokasi: "Kaligangsa, Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Anggrek",
    npsn: "69914319",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    lokasi: "Kaligangsa, Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Sakura",
    npsn: "70035705",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    lokasi: "Kaligangsa, Margadana, Kota Tegal",
  },
  // Pesurungan Lor (3 Lembaga)
  {
    nama: "RA Baitul Iman",
    npsn: "69743497",
    jenis_institusi: "RA",
    kecamatan: "Margadana",
    kelurahan: "Pesurungan Lor",
    rw: "01",
    rt: "04",
    lokasi: "Jl. Banjarmasin RT 04/RW 01, Pesurungan Lor, Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Insan Cendikia",
    npsn: "69935483",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Pesurungan Lor",
    lokasi: "Pesurungan Lor, Margadana, Kota Tegal",
  },
  {
    nama: "TK Mubarokah",
    npsn: "70052167",
    jenis_institusi: "TK",
    kecamatan: "Margadana",
    kelurahan: "Pesurungan Lor",
    lokasi: "Pesurungan Lor, Margadana, Kota Tegal",
  },
  // Sumurpanggang (7 Lembaga)
  {
    nama: "KB Insan Cerdas",
    npsn: "69818077",
    jenis_institusi: "KB",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    lokasi: "Sumurpanggang, Margadana, Kota Tegal",
  },
  {
    nama: "PAUD TPQ Fahmal Qur'an",
    npsn: "69904186",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    lokasi: "Sumurpanggang, Margadana, Kota Tegal",
  },
  {
    nama: "PKBM Ki Hajar Dewantara",
    npsn: "P9959949",
    jenis_institusi: "PKBM",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    lokasi: "Sumurpanggang, Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Seruni Sumurpanggang",
    npsn: "69908953",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    lokasi: "Sumurpanggang, Margadana, Kota Tegal",
  },
  {
    nama: "TK Aisyiyah Bustanul Athfal X",
    npsn: "20351676",
    jenis_institusi: "TK",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    lokasi: "Sumurpanggang, Margadana, Kota Tegal",
  },
  {
    nama: "TK Masyithoh VII",
    npsn: "20351682",
    jenis_institusi: "TK",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    lokasi: "Sumurpanggang, Margadana, Kota Tegal",
  },
  {
    nama: "TK Tarbiyatul Islamiyah",
    npsn: "20351681",
    jenis_institusi: "TK",
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    lokasi: "Sumurpanggang, Margadana, Kota Tegal",
  },
  // Krandon (4 Lembaga)
  {
    nama: "KB Telaga Ilmu",
    npsn: "69915012",
    jenis_institusi: "KB",
    kecamatan: "Margadana",
    kelurahan: "Krandon",
    lokasi: "Krandon, Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Tunas Bangsa",
    npsn: "69914286",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Krandon",
    lokasi: "Krandon, Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Tunas Harapan Krandon",
    npsn: "69908672",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Krandon",
    lokasi: "Krandon, Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Tunas Muda",
    npsn: "69915008",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Krandon",
    lokasi: "Krandon, Margadana, Kota Tegal",
  },
  // Cabawan (2 Lembaga)
  {
    nama: "PAUD TPQ At Taqwa",
    npsn: "69818096",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Cabawan",
    lokasi: "Cabawan, Margadana, Kota Tegal",
  },
  {
    nama: "Pos PAUD Tunas Ceria",
    npsn: "69915007",
    jenis_institusi: "SPS",
    kecamatan: "Margadana",
    kelurahan: "Cabawan",
    lokasi: "Cabawan, Margadana, Kota Tegal",
  },
];

/**
 * Generator Master Seed Item untuk seluruh Satuan PAUD & PKBM Kota Tegal
 */
export function buildPaudMasterSeed(): MasterKomunitasSeedItem[] {
  return RAW_PAUD_PKBM_TEGAL.map((item, index) => {
    const kecSlug = slugify(item.kecamatan);
    const kelSlug = slugify(item.kelurahan);
    const nameSlug = slugify(item.nama);
    const id = `kom-paud-${kecSlug}-${kelSlug}-${nameSlug}`;
    const rw = (item.rw || `0${(index % 6) + 1}`).padStart(2, "0");
    const rt = (item.rt || `0${(index % 4) + 1}`).padStart(2, "0");

    const jenisDisplay = item.jenis_institusi || "PAUD";
    const npsnInfo = item.npsn ? ` [NPSN: ${item.npsn}]` : "";

    return {
      id,
      nama: item.nama,
      jenis: "satuan_paud",
      kecamatan: item.kecamatan,
      kelurahan: item.kelurahan,
      rt,
      rw,
      lokasi:
        item.lokasi ||
        `Gedung ${item.nama}, Kel. ${item.kelurahan}, Kec. ${item.kecamatan}, Kota Tegal`,
      deskripsi:
        item.deskripsi ||
        `Satuan Pendidikan Anak Usia Dini / Nonformal (${jenisDisplay}) ${item.nama}${npsnInfo} di Kelurahan ${item.kelurahan}, Kecamatan ${item.kecamatan}, Kota Tegal yang menyelenggarakan stimulasi tumbuh kembang, kesiapan belajar anak, dan pendidikan karakter.`,
      kontak: item.kontak || `0813-5566-${String(2000 + index).padStart(4, "0")} (Pengelola / Kepala Sekolah)`,
      jadwal:
        item.jadwal ||
        (item.jenis_institusi === "TPA"
          ? "Senin s/d Sabtu, Pukul 07.00 - 16.00 WIB"
          : "Senin s/d Jumat, Pukul 07.30 - 11.00 WIB"),
    };
  });
}

export const SEED_PAUD_PKBM_TEGAL: MasterKomunitasSeedItem[] = buildPaudMasterSeed();
